---
abstract: 'Swish-e 2.x server with OpenSearch results'
author:
  - 'Peter Karman <karman@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Search-OpenSearch-Engine-SWISH
no_index:
  directory:
    - t
    - inc
requires:
  SWISH::Prog: 0.37
  Search::OpenSearch: 0
  Test::More: 0
version: 0.04
